[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["pyHeka", "pyHeka.FileFormat"]

[project]
name = "pyHeka"
version = "1.0.0"
description = "Heka Dat File Reader"
readme = "README.md"
authors = [
    { name = "Igor Delvendahl", email = "igor.delvendahl@physiologie.uni-freiburg.de" },
]
dependencies = [
    "numpy>=1.20.0",
]
requires-python = ">=3.9"

[project.urls]
Homepage = "https://github.com/delvendahl/HekaDatReader"