[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "HekaDatReader"
version = "0.0beta"
description = "Heka Dat File Reader"
long_description = "Python reader for bundled .dat files from Heka Pathcmaster software."
url = "https://github.com/delvendahl/HekaDatReader"
readme = "README.md"
authors = [
    { name = "Igor Delvendahl", email = "igor.delvendahl@physiologie.uni-freiburg.de" },
]
dependencies = [
    "numpy>=1.20.0",
]
requires-python = ">=3.9"